version: '3.8'
services:
  gremlin-server:
    image: janusgraph/janusgraph:latest
    ports:
      - 8182:8182
    networks:
      - QuantumSupplyChain
    environment:
      - JAVA_OPTIONS=-Xss5m
    volumes:
      - ./:/app:z
      - ./scripts:/docker-entrypoint-initdb.d
  gremlin-visualizer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - gremlin-server
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - QuantumSupplyChain
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_HOST=gremlin-server

networks:
  QuantumSupplyChain:
    driver: bridge
